# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 00cc2d613c2a2adcf9dc406f08ce3e67c9b818e1f83219915bfa7e25915c961d1e5ea39c346bcb36b7db844f2f947b07f7951184a06e51bd71cce8b4f8953ad7

test:
  secret_key_base: d235ff73ede9432e5650472f30da3c38304fa81c93ec91bbdabe1a95ced565bb009cf3a5d63166b4ebdf785e70b303f99b0d5946b08640452af877ca51b08bdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
