source "http://rubygems.org"

gem 'sinatra', '~> 1.4', '>= 1.4.6'
gem 'activerecord', '~> 4.2', '>= 4.2.5'
gem 'sinatra-activerecord', '~> 2.0', '>= 2.0.9'
gem 'sqlite3', '~> 1.3', '>= 1.3.11'
gem 'rake'